"""Verified registry of assets across BIST, Crypto, and Global Equities."""

from marketpulse.models import Asset, AssetType

ASSET_DATABASE: list[Asset] = [
    # --- BIST 100 HİSSELERİ ---
    Asset(
        symbol="THYAO",
        name="Türk Hava Yolları",
        asset_type=AssetType.BIST,
        sector="Ulaştırma & Havacılık",
        currency="TRY",
        exchange="BIST",
        description_tr="Türkiye'nin bayrak taşıyıcı ulusal havayolu şirketi. Global uçuş ağı ve kargo operasyonları.",
        description_en="Flag carrier airline of Turkey with an expansive international flight and cargo network.",
        dividend_yield=0.0,
        payout_month="-",
    ),
    Asset(
        symbol="ASELS",
        name="Aselsan",
        asset_type=AssetType.BIST,
        sector="Savunma Sanayii & Teknoloji",
        currency="TRY",
        exchange="BIST",
        description_tr="Elektronik, radar, aviyonik ve elektro-optik sistemler geliştiren lider savunma teknolojisi şirketi.",
        description_en="Premier defense electronics contractor specializing in communication, radar, and electronic warfare systems.",
        dividend_yield=1.8,
        payout_month="Kasım / Nov",
    ),
    Asset(
        symbol="EREGL",
        name="Ereğli Demir Çelik",
        asset_type=AssetType.BIST,
        sector="Demir Çelik & Metal",
        currency="TRY",
        exchange="BIST",
        description_tr="Türkiye'nin en büyük yassı çelik üreticisi, entegre demir-çelik sanayi devi.",
        description_en="Turkey's largest flat steel producer and integrated industrial steel conglomerate.",
        dividend_yield=8.4,
        payout_month="Mart / Mar",
    ),
    Asset(
        symbol="GARAN",
        name="Garanti BBVA",
        asset_type=AssetType.BIST,
        sector="Bankacılık & Finans",
        currency="TRY",
        exchange="BIST",
        description_tr="Türkiye'nin en büyük özel mevduat ve dijital bankacılık kuruluşlarından biri.",
        description_en="One of Turkey's leading private banking and digital financial services institutions.",
        dividend_yield=3.5,
        payout_month="Nisan / Apr",
    ),
    Asset(
        symbol="SASA",
        name="Sasa Polyester",
        asset_type=AssetType.BIST,
        sector="Kimya & Tekstil Hammaddesi",
        currency="TRY",
        exchange="BIST",
        description_tr="Polyester elyaf, filament iplik ve polimer bazlı özel kimyasal ürünler üreticisi.",
        description_en="Major manufacturer of polyester fiber, filament yarn, and specialty polymer products.",
        dividend_yield=0.0,
        payout_month="-",
    ),
    Asset(
        symbol="TUPRS",
        name="Tüpraş",
        asset_type=AssetType.BIST,
        sector="Enerji & Petrol Rafineri",
        currency="TRY",
        exchange="BIST",
        description_tr="Türkiye'nin en büyük sanayi kuruluşu ve 4 rafinerisiyle tek petrol rafine edicisi.",
        description_en="Turkey's largest industrial enterprise and primary petroleum refiner operating 4 domestic refineries.",
        dividend_yield=9.8,
        payout_month="Eylül / Sep",
    ),
    Asset(
        symbol="KCHOL",
        name="Koç Holding",
        asset_type=AssetType.BIST,
        sector="Holding & Yatırım",
        currency="TRY",
        exchange="BIST",
        description_tr="Enerji, otomotiv, tüketim malları ve finans sektörlerinde faaliyet gösteren en büyük holding.",
        description_en="Turkey's largest industrial and commercial conglomerate spanning energy, automotive, finance, and consumer goods.",
        dividend_yield=4.2,
        payout_month="Nisan / Apr",
    ),
    Asset(
        symbol="BIMAS",
        name="BİM Birleşik Mağazalar",
        asset_type=AssetType.BIST,
        sector="Perakende Ticaret",
        currency="TRY",
        exchange="BIST",
        description_tr="Türkiye genelinde yaygın indirim marketleri zinciri ve gıda perakendecisi.",
        description_en="Leading hard-discount supermarket chain with thousands of stores across Turkey.",
        dividend_yield=3.8,
        payout_month="Mayıs / May",
    ),
    Asset(
        symbol="AKBNK",
        name="Akbank",
        asset_type=AssetType.BIST,
        sector="Bankacılık & Finans",
        currency="TRY",
        exchange="BIST",
        description_tr="Geniş şube ağı ve yenilikçi mobil bankacılık hizmetleriyle önde gelen ticari banka.",
        description_en="Prominent commercial bank providing retail, commercial, and investment banking services.",
        dividend_yield=3.9,
        payout_month="Nisan / Apr",
    ),
    Asset(
        symbol="SISE",
        name="Şişecam",
        asset_type=AssetType.BIST,
        sector="Cam & Kimyasallar",
        currency="TRY",
        exchange="BIST",
        description_tr="Düzcam, cam ev eşyası, cam ambalaj ve soda kimyasallarında küresel pazar lideri.",
        description_en="Global manufacturer of flat glass, glassware, glass packaging, and soda ash chemicals.",
        dividend_yield=2.9,
        payout_month="Mayıs / May",
    ),

    # --- KRİPTO PARALAR (CRYPTO) ---
    Asset(
        symbol="BTC",
        name="Bitcoin",
        asset_type=AssetType.CRYPTO,
        sector="Katman 1 / Değer Saklama",
        currency="USD",
        exchange="Crypto",
        description_tr="Merkeziyetsiz, eşler arası dijital para birimi ve küresel dijital altın standardı.",
        description_en="Decentralized peer-to-peer digital cryptocurrency and the premier digital store of value.",
    ),
    Asset(
        symbol="ETH",
        name="Ethereum",
        asset_type=AssetType.CRYPTO,
        sector="Akıllı Sözleşmeler / Katman 1",
        currency="USD",
        exchange="Crypto",
        description_tr="Akıllı sözleşmeleri ve merkeziyetsiz uygulamaları (dApp) çalıştıran lider blokzincir platformu.",
        description_en="Decentralized, open-source blockchain enabling smart contracts and decentralized applications (dApps).",
    ),
    Asset(
        symbol="SOL",
        name="Solana",
        asset_type=AssetType.CRYPTO,
        sector="Yüksek Hızlı Katman 1",
        currency="USD",
        exchange="Crypto",
        description_tr="Yüksek işlem hacmi, ultra düşük işlem ücretleri ve DeFi/NFT odaklı yüksek performanslı ağ.",
        description_en="High-throughput, ultra-low latency blockchain engineered for high-frequency DeFi and web3 applications.",
    ),
    Asset(
        symbol="AVAX",
        name="Avalanche",
        asset_type=AssetType.CRYPTO,
        sector="Alt Ağlar / Katman 1",
        currency="USD",
        exchange="Crypto",
        description_tr="Alt ağ (subnet) mimarisine ve hızlı mutabakata sahip ölçeklenebilir blokzincir platformu.",
        description_en="Fast, scalable smart contract platform utilizing unique subnet architecture and rapid consensus.",
    ),
    Asset(
        symbol="XRP",
        name="Ripple",
        asset_type=AssetType.CRYPTO,
        sector="Sınır Ötesi Ödemeler",
        currency="USD",
        exchange="Crypto",
        description_tr="Bankalar ve finansal kuruluşlar arasında anlık, düşük maliyetli sınır ötesi transfer protokolü.",
        description_en="Real-time gross settlement system and remittance network built for enterprise institutional settlements.",
    ),
    Asset(
        symbol="BNB",
        name="BNB",
        asset_type=AssetType.CRYPTO,
        sector="Borsa & BSC Ekosistemi",
        currency="USD",
        exchange="Crypto",
        description_tr="BNB Chain ekosisteminin yerel hizmet ve işlem ücreti token'ı.",
        description_en="Native ecosystem token powering BNB Smart Chain and Binance ecosystem transactions.",
    ),
    Asset(
        symbol="LINK",
        name="Chainlink",
        asset_type=AssetType.CRYPTO,
        sector="Merkeziyetsiz Oracle / Veri",
        currency="USD",
        exchange="Crypto",
        description_tr="Akıllı sözleşmeleri gerçek dünya finans verileri ve API'lar ile bağlayan güvenilir oracle ağı.",
        description_en="Decentralized oracle network connecting blockchains with off-chain financial and real-world data feeds.",
    ),
    Asset(
        symbol="NEAR",
        name="NEAR Protocol",
        asset_type=AssetType.CRYPTO,
        sector="Sharding / Katman 1",
        currency="USD",
        exchange="Crypto",
        description_tr="Nightshade sharding teknolojisi ile geliştirici dostu, ölçeklenebilir blokzincir protokolü.",
        description_en="Developer-focused layer-one blockchain featuring Nightshade sharding for global scalability.",
    ),

    # --- KÜRESEL HİSSELER (GLOBAL EQUITIES / US) ---
    Asset(
        symbol="AAPL",
        name="Apple Inc.",
        asset_type=AssetType.GLOBAL,
        sector="Tüketici Elektroniği & Yazılım",
        currency="USD",
        exchange="NASDAQ",
        description_tr="iPhone, Mac, iPad donanımları ve App Store, iCloud gibi dijital hizmetler devi.",
        description_en="Global technology company designing iPhones, Macs, operating systems, and ecosystem services.",
    ),
    Asset(
        symbol="NVDA",
        name="NVIDIA Corporation",
        asset_type=AssetType.GLOBAL,
        sector="Yarı İletken & Yapay Zeka Donanımı",
        currency="USD",
        exchange="NASDAQ",
        description_tr="Yapay zeka modellerini eğiten GPU'ların ve veri merkezi donanımlarının küresel lideri.",
        description_en="World leader in graphics processing units (GPUs) and accelerated computing for modern AI.",
    ),
    Asset(
        symbol="MSFT",
        name="Microsoft Corporation",
        asset_type=AssetType.GLOBAL,
        sector="Yazılım & Bulut Bilişim",
        currency="USD",
        exchange="NASDAQ",
        description_tr="Windows, Office 365, Azure bulut altyapısı ve yapay zeka ortaklıkları devi.",
        description_en="Multinational software and cloud computing leader behind Windows, Office 365, and Azure.",
    ),
    Asset(
        symbol="TSLA",
        name="Tesla Inc.",
        asset_type=AssetType.GLOBAL,
        sector="Elektrikli Araçlar & Enerji",
        currency="USD",
        exchange="NASDAQ",
        description_tr="Elektrikli otomotiv, otonom sürüş yazılımları ve batarya enerji depolama sistemleri.",
        description_en="Electric vehicle pioneer and clean energy company advancing autonomous driving technology.",
    ),
    Asset(
        symbol="AMZN",
        name="Amazon.com Inc.",
        asset_type=AssetType.GLOBAL,
        sector="E-Ticaret & AWS Bulut",
        currency="USD",
        exchange="NASDAQ",
        description_tr="Dünyanın en büyük e-ticaret platformu ve pazar lideri AWS bulut sağlayıcısı.",
        description_en="Global e-commerce marketplace giant and world-leading cloud infrastructure provider (AWS).",
    ),
]


class AssetRegistry:
    def __init__(self, assets: list[Asset] | None = None):
        self._assets = assets if assets is not None else list(ASSET_DATABASE)
        self._by_symbol = {a.symbol.upper(): a for a in self._assets}

    def list_all(self, asset_type: str | None = None) -> list[Asset]:
        if not asset_type or asset_type.lower() == "all":
            return list(self._assets)
        return [a for a in self._assets if a.asset_type.value == asset_type.lower()]

    def get_by_symbol(self, symbol: str) -> Asset | None:
        return self._by_symbol.get(symbol.strip().upper())
